services:
  postgres:
    image: postgres:18
    #restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/18/docker

    networks:
      - dev-network

    cpus: 2
    mem_limit: 2g

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    security_opt:
      - "no-new-privileges:true"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

networks:
  dev-network:
    external: true
    name: dev-network
